import * as vscode from 'vscode';
import type { AtlasConfig } from '../config';
import { render } from '../render/renderer';
import { isExternalHref, resolveDocumentHref, splitHref } from '../resource';
import { getTheme } from '../themes';

/** Written into every export so a later overwrite can recognise its own output. */
export const EXPORT_MARKER = '<!-- Generated by Markdown Atlas -->';

const IMAGE_MIME: Record<string, string> = {
	'.png': 'image/png',
	'.jpg': 'image/jpeg',
	'.jpeg': 'image/jpeg',
	'.gif': 'image/gif',
	'.svg': 'image/svg+xml',
	'.webp': 'image/webp',
	'.avif': 'image/avif',
	'.bmp': 'image/bmp',
	'.ico': 'image/x-icon',
};

/** Above this an inlined image bloats the file more than it helps portability. */
const MAX_EMBED_BYTES = 8 * 1024 * 1024;

export interface PrintOptions {
	pageSize: string;
	margin: string;
}

export interface StandaloneOptions {
	/**
	 * Present when the HTML is headed for the PDF renderer. That page is printed
	 * from a blank frame with no base URL, so relative image paths cannot
	 * resolve — embedding is forced on, with a much higher size ceiling.
	 */
	print?: PrintOptions;
}

export async function buildStandaloneHtml(
	extensionUri: vscode.Uri,
	resource: vscode.Uri,
	text: string,
	config: AtlasConfig,
	options: StandaloneOptions = {},
): Promise<string> {
	const renderOptions = {
		frontMatter: config.frontMatter,
		math: config.math,
		codeCopyButton: false,
	};

	// First pass only collects the hrefs; reading them is async, and the
	// renderer's resolver is not. The second pass renders with the answers.
	const requested = new Set<string>();
	render(text, { ...renderOptions, resolveResource: href => (requested.add(href), href) });

	const embed = options.print ? true : config.exportEmbedImages;
	const limit = options.print ? 64 * 1024 * 1024 : MAX_EMBED_BYTES;
	const embedded = embed
		? await embedImages(resource, requested, limit)
		: new Map<string, string>();

	const { html, title } = render(text, {
		...renderOptions,
		resolveResource: href => embedded.get(href) ?? href,
	});

	const theme = getTheme(config.theme);
	const styles = [
		html.includes('katex') ? await readKatexCss(extensionUri) : '',
		await readMedia(extensionUri, 'base.css'),
		await readMedia(extensionUri, 'code.css'),
		await readMedia(extensionUri, 'themes', `${theme.id}.css`),
		await readMedia(extensionUri, 'export.css'),
		pageVariables(config, options.print),
		config.customCss,
	].filter(Boolean);

	const documentTitle = title || (resource.path.split('/').pop() ?? 'Document');
	// `auto` follows the editor's colour theme, which an exported file does not have.
	const codeScheme = theme.codeScheme === 'auto' ? 'light' : theme.codeScheme;

	return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>${escapeHtml(documentTitle)}</title>
${EXPORT_MARKER}
${styles.map(css => `<style>\n${css}\n</style>`).join('\n')}
</head>
<body class="atlas-body" data-code-scheme="${codeScheme}">
<main class="atlas-export-page">
<article class="atlas-content" dir="auto">
${html}
</article>
</main>
</body>
</html>
`;
}

function pageVariables(config: AtlasConfig, print: PrintOptions | undefined): string {
	const root = `:root {\n\t--atlas-font-size: ${config.fontSize}px;\n\t--atlas-line-width: ${config.lineWidth}px;\n\t--atlas-zoom: 1;\n}`;
	if (!print) {
		return root;
	}

	// Printing drops backgrounds unless the page opts in, which would strip every
	// theme's blockquote and code-block fills. The renderer asks for them over
	// the protocol too; this covers the file being opened and printed by hand.
	return `${root}

@page {
	size: ${print.pageSize};
	margin: ${print.margin};
}

html,
body.atlas-body {
	-webkit-print-color-adjust: exact;
	print-color-adjust: exact;
}

.atlas-export-page {
	padding: 0;
}

.atlas-content {
	max-width: none;
}`;
}

async function embedImages(
	resource: vscode.Uri,
	hrefs: Iterable<string>,
	limit: number,
): Promise<Map<string, string>> {
	const embedded = new Map<string, string>();

	for (const href of hrefs) {
		if (isExternalHref(href)) {
			continue;
		}
		const target = resolveDocumentHref(resource, href);
		if (!target) {
			continue;
		}

		const extension = /\.[^./]*$/.exec(splitHref(href).file.toLowerCase())?.[0] ?? '';
		const mime = IMAGE_MIME[extension];
		if (!mime) {
			continue;
		}

		try {
			const bytes = await vscode.workspace.fs.readFile(target);
			if (bytes.byteLength <= limit) {
				embedded.set(href, `data:${mime};base64,${Buffer.from(bytes).toString('base64')}`);
			}
		} catch {
			// Missing or unreadable: leave the original href so the broken link
			// is visible in the export rather than silently blank.
		}
	}

	return embedded;
}

/** KaTeX's stylesheet points at font files beside it; fold those in as data URIs. */
async function readKatexCss(extensionUri: vscode.Uri): Promise<string> {
	const css = await readMedia(extensionUri, 'vendor', 'katex', 'katex.min.css');
	const fonts = new Map<string, string>();

	for (const [, name] of css.matchAll(/url\(fonts\/([^)]+\.woff2)\)/g)) {
		if (fonts.has(name)) {
			continue;
		}
		try {
			const bytes = await vscode.workspace.fs.readFile(
				vscode.Uri.joinPath(extensionUri, 'media', 'vendor', 'katex', 'fonts', name),
			);
			fonts.set(name, `data:font/woff2;base64,${Buffer.from(bytes).toString('base64')}`);
		} catch {
			// Leave the rule alone; the browser will just skip that face.
		}
	}

	// Drop the ttf/woff fallbacks: only woff2 ships, so those urls are dead ends.
	return css
		.replace(/url\(fonts\/([^)]+\.woff2)\)/g, (match, name: string) => {
			const data = fonts.get(name);
			return data ? `url(${data})` : match;
		})
		.replace(/,?url\(fonts\/[^)]+\.(?:ttf|woff)\)\s*format\("(?:truetype|woff)"\)/g, '');
}

async function readMedia(extensionUri: vscode.Uri, ...parts: string[]): Promise<string> {
	const bytes = await vscode.workspace.fs.readFile(
		vscode.Uri.joinPath(extensionUri, 'media', ...parts),
	);
	return Buffer.from(bytes).toString('utf8');
}

function escapeHtml(value: string): string {
	return value
		.replace(/&/g, '&amp;')
		.replace(/</g, '&lt;')
		.replace(/>/g, '&gt;')
		.replace(/"/g, '&quot;');
}
